import Head from "next/head";
import { Form, Input, Button, Select, DatePicker, Space } from "antd";
import "antd/dist/antd.css";
import Sidebar from "../components/Sidebar";

export default function Home() {
  const { Option } = Select;
  const { RangePicker } = DatePicker;
  function onChange(value) {
    console.log(`selected ${value}`);
  }

  function onSearch(val) {
    console.log("search:", val);
  }
  const onFinish = (values) => {
    console.log("Success:", values);
  };

  return (
    <div>
      <Head>
        <title>Luccrostrength</title>
        <meta name="Luccrostrength" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dashboard">
        <Sidebar />
        <div className="main-content">
          <div className="white-box">
            <Form name="horizontal_login" layout="inline" onFinish={onFinish}>
              <Form.Item label="Currencies" name="currencies">
                <Select
                  showSearch
                  placeholder="Select"
                  optionFilterProp="children"
                  onChange={onChange}
                  onSearch={onSearch}
                  filterOption={(input, option) =>
                    option.children
                      .toLowerCase()
                      .indexOf(input.toLowerCase()) >= 0
                  }
                  style={{ width: "150px" }}
                >
                  <Option value="GBP_JPY">GBP_JPY</Option>
                  <Option value="EUR_USD">EUR_USD</Option>
                  <Option value="NZD_USD">NZD_USD</Option>
                  <Option value="USD_CHF">USD_CHF</Option>
                  <Option value="AUD_CHF">AUD_CHF</Option>
                  <Option value="CAD_CHF">CAD_CHF</Option>
                  <Option value="AUD_NZD">AUD_NZD</Option>
                  <Option value="NZD_CHF">NZD_CHF</Option>
                  <Option value="CHF_JPY">CHF_JPY</Option>
                  <Option value="NZD_CAD">NZD_CAD</Option>
                  <Option value="NZD_JPY">NZD_JPY</Option>
                  <Option value="GBP_CAD">GBP_CAD</Option>
                  <Option value="EUR_CAD">EUR_CAD</Option>
                  <Option value="EUR_GBP">EUR_GBP</Option>
                  <Option value="GBP_AUD">GBP_AUD</Option>
                  <Option value="EUR_JPY">EUR_JPY</Option>
                  <Option value="AUD_USD">AUD_USD</Option>
                  <Option value="GBP_CHF">GBP_CHF</Option>
                  <Option value="GBP_NZD">GBP_NZD</Option>
                  <Option value="GBP_USD">GBP_USD</Option>
                  <Option value="USD_CAD">USD_CAD</Option>
                  <Option value="USD_JPY">USD_JPY</Option>
                  <Option value="EUR_CHF">EUR_CHF</Option>
                  <Option value="AUD_JPY">AUD_JPY</Option>
                  <Option value="EUR_AUD">EUR_AUD</Option>
                  <Option value="EUR_NZD">EUR_NZD</Option>
                  <Option value="CAD_JPY">CAD_JPY</Option>
                </Select>
              </Form.Item>
              <Form.Item label="Dataset" name="dataset">
                <Select style={{ width: "150px" }}>
                  <Option value="train">train</Option>
                  <Option value="test">test</Option>
                  <Option value="valid">valid</Option>
                </Select>
              </Form.Item>
              <Form.Item label="Model" name="model">
                <Select style={{ width: "150px" }}>
                  <Option value="CNN_NEW_TDC">CNN_NEW_TDC</Option>
                </Select>
              </Form.Item>
              <Form.Item label="Time Frames" name="timeframe">
                <Select style={{ width: "150px" }}>
                  <Option value="M15">M15</Option>
                  <Option value="M30">M30</Option>
                  <Option value="M60">M60</Option>
                  <Option value="M240">M240</Option>
                  <Option value="M1440">M1440</Option>
                </Select>
              </Form.Item>
              <Form.Item label="Date" name="date">
                <RangePicker showTime />
              </Form.Item>
              <Form.Item>
                <Button type="primary" htmlType="submit">
                  Submit
                </Button>
              </Form.Item>
            </Form>
          </div>
          <div className="white-box">
            <h2>Chart</h2>
          </div>
        </div>
      </main>
    </div>
  );
}
