import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Form, Button, Select, DatePicker, Spin, Row, Col } from "antd";
import "antd/dist/antd.css";
import Sidebar from "../components/Sidebar";
import AnyChart from "anychart-react";
import anychart from "anychart";
import axios from "axios";

export default function strength() {
  const [loading, setLoading] = useState(false);
  const [isChart, setIsChart] = useState(false);
  const [dateRange, setDateRange] = useState([]);
  useEffect(() => {
    // Update the document title using the browser API
    // onFinish();
  });
  const { Option } = Select;
  const { RangePicker } = DatePicker;

  function onChangeDate(value, dateString) {
    setDateRange(dateString);
  }

  const onFinish = (values) => {
    var dateFrom = "";
    var dateTo = "";
    if (dateRange.length > 0) {
      console.log(dateRange[0]);
      dateFrom = dateRange[0];
      dateTo = dateRange[1];
    }
    setLoading(true);
    const formData = {
      timeframe: values.timeframe,
      to: dateTo,
      from: dateFrom,
    };
    //return false;
    axios({
      method: "post",
      headers: { "Content-Type": "application/json" },
      url: `${process.env.API_URL}strength_data`,
      data: formData,
    })
      .then((res) => {
        //console.log("res", res);
        // return false;
        const keyArray = Object.keys(res.data.data);
        const analogKey = keyArray[0];
        const digitalKey = keyArray[1];
        var analogData = res.data.data[analogKey];
        var digitalData = res.data.data[digitalKey];
        console.log("digitalData", digitalData);
        // ============= Chart Configuration ==========
        var offset = new Date().getTimezoneOffset();
        anychart.format.outputTimezone(offset);

        // ============= Chart Configuration ==========

        setLoading(false);
      })
      .catch(function (error) {
        console.log(error);
        setLoading(false);
      });
  };
  //========= Chart=======

  return (
    <div>
      <Head>
        <title>Luccrostrength</title>
        <meta name="Luccrostrength" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.anychart.com/releases/8.3.0/css/anychart-ui.min.css"
        />
      </Head>

      <main className="dashboard">
        <Sidebar />
        <div className="main-content">
          <div className="white-box">
            <Form
              name="horizontal_login"
              layout="inline"
              initialValues={{
                timeframe: "M240",
              }}
              onFinish={onFinish}
            >
              <Form.Item label="Time Frames" name="timeframe">
                <Select style={{ width: "100px" }}>
                  <Option value="M15">M15</Option>
                  <Option value="M30">M30</Option>
                  <Option value="M60">M60</Option>
                  <Option value="M240">M240</Option>
                  <Option value="M1440">M1440</Option>
                </Select>
              </Form.Item>
              <Form.Item label="Date" name="date">
                <RangePicker
                  showTime
                  onChange={onChangeDate}
                  style={{ width: "300px" }}
                />
              </Form.Item>
              <Form.Item>
                <Button type="primary" htmlType="submit">
                  Submit
                </Button>
              </Form.Item>
            </Form>
          </div>
          <Spin tip="Loading..." spinning={loading}>
            <Row gutter={16}>
              <Col className="gutter-row" span={12}>
                <div className="white-box">
                  <h2>Analog</h2>
                  <div id="analogContainer"></div>
                </div>
              </Col>
              <Col className="gutter-row" span={12}>
                <div className="white-box">
                  <h2>Digital</h2>
                </div>
              </Col>
            </Row>
          </Spin>
        </div>
      </main>
    </div>
  );
}
