import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Form, Button, Select, DatePicker, Spin, Row, Col } from "antd";
import "antd/dist/antd.css";
import Sidebar from "../components/Sidebar";
import anychart from "anychart";
import axios from "axios";

export default function Strength() {
  const [loading, setLoading] = useState(false);
  const [dateRange, setDateRange] = useState([]);

  const { Option } = Select;
  const { RangePicker } = DatePicker;

  function onChangeDate(value, dateString) {
    setDateRange(dateString);
  }

  const onFinish = (values) => {
    var dateFrom = "";
    var dateTo = "";
    if (dateRange.length > 0) {
      console.log(dateRange[0]);
      dateFrom = dateRange[0];
      dateTo = dateRange[1];
    }
    setLoading(true);
    const formData = {
      timeframe: values.timeframe,
      to: dateTo,
      from: dateFrom,
    };
    //return false;
    axios({
      method: "post",
      headers: { "Content-Type": "application/json" },
      url: `${process.env.API_URL}strength_data`,
      data: formData,
    })
      .then((res) => {
        // console.log("res", res);
        // return false;
        const keyArray = Object.keys(res.data.data);
        const analogKey = keyArray[1];
        const digitalKey = keyArray[2];
        var analogData = res.data.data[analogKey];
        var digitalData = res.data.data[digitalKey];
        // ============= Chart Configuration ==========
        var offset = new Date().getTimezoneOffset();
        anychart.format.outputTimezone(offset);
        analogChart(analogData);
        // digitalChart(digitalData);
        // ============= Chart Configuration ==========

        setLoading(false);
      })
      .catch(function (error) {
        console.log(error);
        setLoading(false);
      });
  };
  // =========== Analog Chart Start ==============
  const analogChart = (analogData) => {
    // set container id for the chart
    const myNode = document.getElementById("analogContainer");
    myNode.innerHTML = "";
    chart.container("analogContainer");
    // initiate chart drawing
    chart.draw();
  };
  // =========== Analog Chart End ================
  // =========== Analog Chart Start ==============

  // =========== Analog Chart End ================

  return (
    <div>
      <Head>
        <title>Luccrostrength</title>
        <meta name="Luccrostrength" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.anychart.com/releases/8.3.0/css/anychart-ui.min.css"
        />
      </Head>

      <main className="dashboard">
        <Sidebar />
        <div className="main-content">
          <div className="white-box">
            <Form
              name="horizontal_login"
              layout="inline"
              initialValues={{
                timeframe: "M240",
              }}
              onFinish={onFinish}
            >
              <Form.Item label="Time Frames" name="timeframe">
                <Select style={{ width: "100px" }}>
                  <Option value="M15">M15</Option>
                  <Option value="M30">M30</Option>
                  <Option value="M60">M60</Option>
                  <Option value="M240">M240</Option>
                  <Option value="M1440">M1440</Option>
                </Select>
              </Form.Item>
              <Form.Item label="Date" name="date">
                <RangePicker
                  showTime
                  onChange={onChangeDate}
                  style={{ width: "300px" }}
                />
              </Form.Item>
              <Form.Item>
                <Button type="primary" htmlType="submit">
                  Submit
                </Button>
              </Form.Item>
            </Form>
          </div>
          <Spin tip="Loading..." spinning={loading}>
            <Row gutter={16}>
              <Col className="gutter-row" span={24}>
                <div className="white-box">
                  <div className="ant-table">
                    <div className="ant-table-container">
                      <div className="ant-table-content">
                        <table>
                          <thead className="ant-table-thead">
                            <tr>
                              <th className="ant-table-cell">Time Frames</th>
                              <th className="ant-table-cell">EUR</th>
                              <th className="ant-table-cell">GBP</th>
                              <th className="ant-table-cell">JPY</th>
                              <th className="ant-table-cell">USD</th>
                              <th className="ant-table-cell">CHF</th>
                              <th className="ant-table-cell">CAD</th>
                              <th className="ant-table-cell">AUD</th>
                              <th className="ant-table-cell">NZD</th>
                            </tr>
                          </thead>
                          <tbody className="ant-table-tbody">
                            <tr className="ant-table-row">
                              <td className="ant-table-cell">
                                <b>M15</b>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "30px" }}
                                      ></div>
                                    </div>
                                    <div>-30</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                            <tr className="ant-table-row">
                              <td className="ant-table-cell">
                                <b>M30</b>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "30px" }}
                                      ></div>
                                    </div>
                                    <div>-30</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                            <tr className="ant-table-row">
                              <td className="ant-table-cell">
                                <b>M60</b>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "30px" }}
                                      ></div>
                                    </div>
                                    <div>-30</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                            <tr className="ant-table-row">
                              <td className="ant-table-cell">
                                <b>M240</b>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "30px" }}
                                      ></div>
                                    </div>
                                    <div>-30</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                            <tr className="ant-table-row">
                              <td className="ant-table-cell">
                                <b>M1140</b>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "30px" }}
                                      ></div>
                                    </div>
                                    <div>-30</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>50</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "40px" }}
                                      ></div>
                                    </div>
                                    <div>-20</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div className="pair">
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>A</b>
                                    </div>
                                    <div className="stacked">
                                      <div className="positive"></div>
                                    </div>
                                    <div>45</div>
                                  </div>
                                  <div className="pair-item anologe-pair">
                                    <div>
                                      <b>B</b>
                                    </div>
                                    <div className="stacked">
                                      <div
                                        className="negative"
                                        style={{ top: "50px" }}
                                      ></div>
                                    </div>
                                    <div>-10</div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </Col>
            </Row>
          </Spin>
        </div>
      </main>
    </div>
  );
}
